### ISSUE TITLE
React Native Modal add onRequestClose

### ISSUE THREAD

**Issue by msvargas** [intergalacticspacehighway/react-native-popper#14]
Hi, Can you add onRequestClose prop in react native modal to dismiss when user press back button?

Thanks

![image](https://user-images.githubusercontent.com/8255332/136856549-4889a466-4b26-4ca2-a206-430d7d262272.png)

**Comment by intergalacticspacehighway** [comment]
@msvargas Thanks. Just released a version 0.3.2 with `onRequestClose`. You can try it out in the latest release `yarn add react-native-popper@latest`
