### ISSUE TITLE
Modal Support

### ISSUE THREAD

**Issue by WildEgo** [intergalacticspacehighway/react-native-popper#4]
Hey guys, I'm trying to use this package currently, I've hit a little bit of a problem tho, when using it in conjunction with the react native modal it causes the popped item to appear below it instead of on top.
Is there any way that behaviour could be changed? If so I'd appreciate it a lot!

Thanks for the amazing package,
Luis Bizarro

**Comment by intergalacticspacehighway** [comment]
@WildEgo Some questions
1. Is it happening on android or iOS?
2. Are you using mode='multiple' option? If yes, try 'single' value. When `single` is used, the popup uses RN's built in Modal. 
3. Is it convenient or possible to keep the <Popover /> code inside of the Modal's body? (This will surely fix it)
If the above doesn't solve it, can you share the code or snack example with a minimum reproducible demo? You can use this template https://snack.expo.io/gCAgexV36

**Comment by vicky-carbon** [comment]
@WildEgo Were you able to find a resolution? I'm encountering the same problem.

It's happening on the web (w/ React Native Web) and `mode="single"` doesn't seem to help.

**Comment by intergalacticspacehighway** [comment]
On web, it's using React portal. I think we can replace it with React Native web's modal. Will look into it.

**Comment by vicky-carbon** [comment]
@intergalacticspacehighway I created a minimal reproduction of this problem [here](https://github.com/vleong2332/repro-rn-popper-visibility).

In my project, I used `patch-package` to change the z-index and it seems to work but that doesn't seem like an ideal solution.
```diff
diff --git a/node_modules/react-native-popper/lib/module/Overlay/Overlay.web.js b/node_modules/react-native-popper/lib/module/Overlay/Overlay.web.js
index 467ce87..ae78656 100644
--- a/node_modules/react-native-popper/lib/module/Overlay/Overlay.web.js
+++ b/node_modules/react-native-popper/lib/module/Overlay/Overlay.web.js
@@ -51,7 +51,7 @@ export function Overlay(props) {
       onClose
     }
   }, /*#__PURE__*/React.createElement(Animated.View, {
-    style: [StyleSheet.absoluteFill, styles],
+    style: [{ zIndex: 9999 }, StyleSheet.absoluteFill, styles],
     pointerEvents: "box-none"
   }, focusable && mode === 'single' ? /*#__PURE__*/React.createElement(FocusScope, {
     contain: trapFocus,

```

**Comment by Y2KForever** [comment]
Did anyone find a solution to this without using `patch-package`? Setting the mode to either `single` or `multiple` does no difference.

**Comment by PabloMD** [comment]
any update on this? xD
