### ISSUE TITLE
Add `onDismiss` prop

### ISSUE THREAD

**Issue by nandorojo** [intergalacticspacehighway/react-native-popper#9]
If we could just forward `onDismiss` down to the modal, then I could refrain from opening other modals until this one is hidden.

**Comment by intergalacticspacehighway** [comment]
@nandorojo Modal is being used as an Overlay by conditional rendering. [Check this out](https://github.com/intergalacticspacehighway/react-native-popper/blob/main/src/Overlay/Overlay.tsx#L35)
Can you use `onOpenChange` to achieve the same or we can add `onDismiss` which gets fired when the exit animation completes?
